
model: 
  type: FDN
  kwargs:
    pd_train: [2, 4, 6, 8]
    pd_test: 2
    pd_pad: 2
    in_ch: 3
    base_dim: 128
    refine_dim: 32
    num_heads: 8
    num_module: 3
    ffn_factor: 2
    
model_input: ['real_noisy_template', 'real_noisy_search']

trainer: Trainer

training:
  dataset: UNIT

  dataset_args:
    add_noise: None # e.g.) None bypass uni-15. gau-15. gau_blind-10.:50. het_gau-10.:50. see more detail in denoise_dataset.py
    crop_size: None
    aug: ['hflip', 'rot']
    n_repeat: 1
    ratio_data: 1
  
  batch_size: 16

  max_epoch: 20
  
  init_lr: 1e-4
  scheduler:
    type: step
    step:
      step_size: 8
      gamma: 0.1
  loss: 1*self_L2+1*tracking_loss
  tmp_info: []
  optimizer:
    type: Adam
    Adam:
      betas: [0.9, 0.999]

  warmup: False
  warmup_iter: 200

validation:
  dataset: None

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: gau_blind-50. # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.
    n_data: 64

  add_con: 0.5
  floor: True

  val: False
  save_image: True
  
  start_epoch: 1
  interval_epoch: 1
  
checkpoint:
  save: True
  start_epoch: 1
  interval_epoch: 1

log:
  interval_iter: 10

test:
  dataset: None

  dataset_args:
    crop_size: None # [64, 64]
    add_noise: None # e.g.) None uni-15. gau-15. gau_blind-10.:50. poi_gau-10.:50.

  add_con: 0.5
  floor: True

  save_image: True